#include <ruby.h>
/* SPDX-License-Identifier: MIT - BRUMA-owned compatibility registration.
 * Keep regex String#[] in native C frames: a Ruby wrapper changes $~ scope. */
static VALUE bruma_legacy_string_aref(int argc, VALUE *argv, VALUE self) {
 if (argc == 1 && (FIXNUM_P(argv[0]) || TYPE(argv[0]) == T_BIGNUM)) {
  long pos = NUM2LONG(argv[0]);
  if (pos < 0) pos += RSTRING_LEN(self);
  if (pos < 0 || pos >= RSTRING_LEN(self)) return Qnil;
  return INT2FIX((unsigned char)RSTRING_PTR(self)[pos]);
 }
 return rb_funcall2(self, rb_intern("bruma_ruby193_native_aref"), argc, argv);
}
static void bruma_init_legacy_string(void) {
 rb_define_alias(rb_cString, "bruma_ruby193_native_aref", "[]");
 rb_define_method(rb_cString, "[]", bruma_legacy_string_aref, -1);
}
void Init_big5(void);
void Init_cp949(void);
void Init_emacs_mule(void);
void Init_encdb(void);
void Init_euc_jp(void);
void Init_euc_kr(void);
void Init_euc_tw(void);
void Init_gb18030(void);
void Init_gb2312(void);
void Init_gbk(void);
void Init_iso_8859_1(void);
void Init_iso_8859_10(void);
void Init_iso_8859_11(void);
void Init_iso_8859_13(void);
void Init_iso_8859_14(void);
void Init_iso_8859_15(void);
void Init_iso_8859_16(void);
void Init_iso_8859_2(void);
void Init_iso_8859_3(void);
void Init_iso_8859_4(void);
void Init_iso_8859_5(void);
void Init_iso_8859_6(void);
void Init_iso_8859_7(void);
void Init_iso_8859_8(void);
void Init_iso_8859_9(void);
void Init_koi8_r(void);
void Init_koi8_u(void);
void Init_shift_jis(void);
void Init_utf_16be(void);
void Init_utf_16le(void);
void Init_utf_32be(void);
void Init_utf_32le(void);
void Init_windows_1251(void);
void Init_big5(void);
void Init_chinese(void);
void Init_emoji(void);
void Init_emoji_iso2022_kddi(void);
void Init_emoji_sjis_docomo(void);
void Init_emoji_sjis_kddi(void);
void Init_emoji_sjis_softbank(void);
void Init_escape(void);
void Init_gb18030(void);
void Init_gbk(void);
void Init_iso2022(void);
void Init_japanese(void);
void Init_japanese_euc(void);
void Init_japanese_sjis(void);
void Init_korean(void);
void Init_single_byte(void);
void Init_transdb(void);
void Init_utf8_mac(void);
void Init_utf_16_32(void);
void Init_zlib(void);
void Init_bruma_trans_big5(void);
void Init_bruma_trans_chinese(void);
void Init_bruma_trans_emoji(void);
void Init_bruma_trans_emoji_iso2022_kddi(void);
void Init_bruma_trans_emoji_sjis_docomo(void);
void Init_bruma_trans_emoji_sjis_kddi(void);
void Init_bruma_trans_emoji_sjis_softbank(void);
void Init_bruma_trans_escape(void);
void Init_bruma_trans_gb18030(void);
void Init_bruma_trans_gbk(void);
void Init_bruma_trans_iso2022(void);
void Init_bruma_trans_japanese(void);
void Init_bruma_trans_japanese_euc(void);
void Init_bruma_trans_japanese_sjis(void);
void Init_bruma_trans_korean(void);
void Init_bruma_trans_newline(void);
void Init_bruma_trans_single_byte(void);
void Init_bruma_trans_transdb(void);
void Init_bruma_trans_utf8_mac(void);
void Init_bruma_trans_utf_16_32(void);
void Init_ext(void) {
 static int initialized=0;
 if(initialized) return;
 initialized=1;
 Init_encdb();
 Init_big5();
 Init_cp949();
 Init_emacs_mule();
 Init_euc_jp();
 Init_euc_kr();
 Init_euc_tw();
 Init_gb18030();
 Init_gb2312();
 Init_gbk();
 Init_iso_8859_1();
 Init_iso_8859_10();
 Init_iso_8859_11();
 Init_iso_8859_13();
 Init_iso_8859_14();
 Init_iso_8859_15();
 Init_iso_8859_16();
 Init_iso_8859_2();
 Init_iso_8859_3();
 Init_iso_8859_4();
 Init_iso_8859_5();
 Init_iso_8859_6();
 Init_iso_8859_7();
 Init_iso_8859_8();
 Init_iso_8859_9();
 Init_koi8_r();
 Init_koi8_u();
 Init_shift_jis();
 Init_utf_16be();
 Init_utf_16le();
 Init_utf_32be();
 Init_utf_32le();
 Init_windows_1251();
 Init_bruma_trans_big5();
 Init_bruma_trans_chinese();
 Init_bruma_trans_emoji();
 Init_bruma_trans_emoji_iso2022_kddi();
 Init_bruma_trans_emoji_sjis_docomo();
 Init_bruma_trans_emoji_sjis_kddi();
 Init_bruma_trans_emoji_sjis_softbank();
 Init_bruma_trans_escape();
 Init_bruma_trans_gb18030();
 Init_bruma_trans_gbk();
 Init_bruma_trans_iso2022();
 Init_bruma_trans_japanese();
 Init_bruma_trans_japanese_euc();
 Init_bruma_trans_japanese_sjis();
 Init_bruma_trans_korean();
 Init_bruma_trans_single_byte();
 Init_bruma_trans_transdb();
 Init_bruma_trans_utf8_mac();
 Init_bruma_trans_utf_16_32();
 bruma_init_legacy_string();
 Init_zlib();
 rb_provide("zlib.so");
 rb_provide("enc/encdb.so");
 rb_provide("enc/trans/transdb.so");
}
