cmake_minimum_required(VERSION 3.22)
project(BrumaNDS LANGUAGES C CXX ASM)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(BUILD_QT_SDL OFF CACHE BOOL "" FORCE)
set(ENABLE_GDBSTUB OFF CACHE BOOL "" FORCE)
set(ENABLE_OGLRENDERER OFF CACHE BOOL "" FORCE)
set(ENABLE_JIT ON CACHE BOOL "" FORCE)
set(ENABLE_LTO_RELEASE OFF CACHE BOOL "" FORCE)
add_subdirectory(../upstream/melonDS melonDS)
add_library(bruma_nds SHARED platform.cpp nds_bridge.cpp)
target_link_libraries(bruma_nds PRIVATE core android log dl)
target_link_options(bruma_nds PRIVATE -Wl,--no-undefined -Wl,-z,max-page-size=16384)
